### ISSUE TITLE
Improve signal strengh color scale

### ISSUE THREAD

**Issue by slamora** [vviudez/guifibaix_map#2]
Follow a known color scale to represent the different levels of signal strengh. For example:
![ppi_scale](https://cloud.githubusercontent.com/assets/4057718/22461042/fdf2f7a4-e7a7-11e6-9568-bb4e9e9e6975.png)

**Comment by vviudez** [comment]
This color scaler is for dBZ, usually for wheater radars (https://en.wikipedia.org/wiki/DBZ_(meteorology)) and not for radio power scale, that, in our case is measured in dBm (https://en.wikipedia.org/wiki/DBm)

I was searching for an standard color scale for dBm, but I can't found any... for that reason I used a simple color scale in the code, based on the real connections we have on our mesh network;

![image](https://cloud.githubusercontent.com/assets/4720407/22461942/a59424a8-e7ab-11e6-8975-9c223c31c349.png)

Of course, we can create a more detalied scale, but working with logic, for example, any connection under -65dBm will use all the transmision capacity for the antenna (in our case, a 802.11n, 150Mbps MIMO antennas), because that, give a color scale under -65dBm is pointless.

**Comment by slamora** [comment]
Yes, you are right, the attached scale is for dBZ. I'm only want to provide an example as reference not to use it as is. In fact I like your scale proposal but I think that could be improved by replacing blue color by dark red. It was very confusing for me seeing the blue color between red and purple.

Just my opinion, anyway I like too much the idea of representing links strengh on a map.
